# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_texttile_segments_cpp <- function(tokens, stopwords, sentence_size, block_size, method, liberal) {
    .Call('_texmer_get_texttile_segments_cpp', PACKAGE = 'texmer', tokens, stopwords, sentence_size, block_size, method, liberal)
}

generate_token_segment_ids_cpp <- function(ntoken_per_doc, nseg_per_doc, segsize_per_doc) {
    .Call('_texmer_generate_token_segment_ids_cpp', PACKAGE = 'texmer', ntoken_per_doc, nseg_per_doc, segsize_per_doc)
}

