# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_token_segment_ids <- function(ntokens_per_doc, nsegments_per_doc, segment_size_per_doc) {
    .Call('_texmer_generate_token_segment_ids', PACKAGE = 'texmer', ntokens_per_doc, nsegments_per_doc, segment_size_per_doc)
}

